name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        target: [test-lib-clj, test-lib-cljs, test-conformance-clj-sync, test-conformance-clj-async, test-conformance-cljs, npm-audit]
    runs-on: ubuntu-latest
    steps:
      - name: yeti-ci
        uses: yetanalytics/yeti-ci-action@v0
        with:
          enable-node: true

      - name: Run make target ${{ matrix.target }}
        run: make ${{ matrix.target }}
