name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        target: [test-lib-clj, test-lib-cljs, test-conformance-clj-sync, test-conformance-clj-async, test-conformance-cljs, npm-audit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup CI Environment
        uses: yetanalytics/action-setup-env@v1

      - name: Run make target ${{ matrix.target }}
        run: make ${{ matrix.target }}
